### ISSUE TITLE
Could not download bundle error

### ISSUE THREAD

**Issue by ajtrichards** [webfactory/create-aws-codedeploy-deployment#1]
Hi.I'm getting the following error messages when using this Action.

```
Run webfactory/create-aws-codedeploy-deployment@v0.1.0
🎋 On branch 'uat', head commit COMMIT
💡 Using appspec.yml -> branch_config 'uat' for branch 'uat'
🎳 Using deployment group 'UAT'
⚙️ Updated deployment group 'UAT'
🚚️ Created deployment d-MYDEPID – https://console.aws.amazon.com/codesuite/codedeploy/deployments/d-MYDEPID?region=eu-west-1
⏲  Waiting for deployment d-MYDEPID to finish
##[error]😱 The deployment d-MYDEPID seems to have failed.
```

The error in Code Deploy is;
> Could not download bundle at 'https://api.github.com/repos/EvaluAgent/MY_REPO/tarball/COMMIT' after 3 retries. Server returned codes: 404 'Not Found'; 404 'Not Found'; 404 'Not Found'; 404 'Not Found'.

Have I missed a step to create this tarball? I didn't see anything in the README that says about another step prior to deploy

**Comment by mpdude** [comment]
Just guessing... did you connect the CodeDeploy application with your repository as described here?

https://docs.aws.amazon.com/codedeploy/latest/userguide/deployments-create-cli-github.html

**Comment by ajtrichards** [comment]
DOH!!! I missed that step - although I was already connected. All working now!!
