### ISSUE TITLE
❓ Found no matching appspec.yml -> branch_config for 'develop' – skipping deployment

### ISSUE THREAD

**Issue by pomcho555** [webfactory/create-aws-codedeploy-deployment#6]
I made "develop" branch and set GitHub actions when this branch is pulled. Of course, the branch has `appspec.yml` on the top of the repository.

After that, I wrote and pushed a tiny code toward "develop" branch, then I got the above error. What is this? It seems like mis-placing `appspec.yml` but I don't. And what to do to solve it?

Thanks

**Comment by mpdude** [comment]
Can you share your workflow configuration and the appspec file?

**Comment by pomcho555** [comment]
I've solved this issue. Just my stupid mistake.

I have 2 AWS accounts for this: Staging and Production. CodeDeploy was provisioned on Production, but my appspec.yml was configured deploying forward to Staging environment. There was no CodeDeploy on Staging!!

Solution:
Just re-configure appspec.yml for getting consistency.

**Comment by mpdude** [comment]
Ok, thanks for the quick reply!
